language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - oraclejdk8

# only `sudo: true` allows running tests on Travis CI container infrastructure for faster builds, but testing installation of .deb makes sense
sudo: true

install:
- cd libbuild && MAVEN_OPTS="-Xmx6g -Xms2g" mvn clean install && cd ..

script:
- MAVEN_OPTS="-Xmx6g -Xms2g" mvn clean install
# test build instructions
- ant
- ant dist
- ant deb
- sudo dpkg -i *.deb
